# Generated by Django 4.1.7 on 2023-02-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_first_name_myuser_last_name_myuser_other_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='other_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
